// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8MV5EVxXFudyt-5w2F1LeDGc9iFj720k',
    appId: '1:839314443613:web:7f50bca81a708abdd66cb4',
    messagingSenderId: '839314443613',
    projectId: 'signin-c8115',
    authDomain: 'signin-c8115.firebaseapp.com',
    storageBucket: 'signin-c8115.appspot.com',
    measurementId: 'G-C1S21KMFD8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUvMM35kT36-F22tyEAuAOyrcuRjQGxww',
    appId: '1:839314443613:android:9fc85709ceeae6bbd66cb4',
    messagingSenderId: '839314443613',
    projectId: 'signin-c8115',
    storageBucket: 'signin-c8115.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYdAOWO_DF67agGc-3B_xtnkDMeWIgfnI',
    appId: '1:839314443613:ios:531a9cca442057ded66cb4',
    messagingSenderId: '839314443613',
    projectId: 'signin-c8115',
    storageBucket: 'signin-c8115.appspot.com',
    iosClientId: '839314443613-r5pi9uf0fptmltf5v2rvfttsvih7oe9s.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYdAOWO_DF67agGc-3B_xtnkDMeWIgfnI',
    appId: '1:839314443613:ios:b8871ac038614206d66cb4',
    messagingSenderId: '839314443613',
    projectId: 'signin-c8115',
    storageBucket: 'signin-c8115.appspot.com',
    iosClientId: '839314443613-5al8471bg4j8duln6mbsjq61c9nhvav1.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushNotification.RunnerTests',
  );
}
